// Exporta la ESTRUCTURA (sin datos) de la base de datos actual a schema.sql,
// leyéndola directo de Postgres — no necesita pg_dump.
//
// Uso (una sola vez, contra la base que ya funciona):
//   DATABASE_URL="postgresql://..." node scripts/exportar-esquema.js
// Genera scripts/schema.sql, que luego usa alta-cliente.js.
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

const url = process.env.DATABASE_URL;
if (!url) { console.error('Falta DATABASE_URL (la base ACTUAL, de la que se copia la estructura).'); process.exit(1); }
const pool = new Pool({ connectionString: url, ssl: /localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL) ? false : { rejectUnauthorized: false } });
const q = (s, p) => pool.query(s, p).then(r => r.rows);
const id = (s) => '"' + String(s).replace(/"/g, '""') + '"';

(async () => {
  const out = [];
  const avisos = [];
  out.push('-- Estructura de Compoint Punto generada por exportar-esquema.js');
  out.push('-- ' + new Date().toISOString());
  out.push('');

  // Tipos enum definidos por el usuario
  const enums = await q(`
    SELECT t.typname, array_agg(e.enumlabel::text ORDER BY e.enumsortorder) AS labels
    FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' GROUP BY t.typname`);
  for (const e of enums) {
    out.push(`CREATE TYPE ${id(e.typname)} AS ENUM (${e.labels.map(l => "'" + l.replace(/'/g, "''") + "'").join(', ')});`);
  }

  const tablas = await q(`
    SELECT c.oid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r' ORDER BY c.relname`);

  for (const t of tablas) {
    const cols = await q(`
      SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS tipo, a.attnotnull,
             pg_get_expr(d.adbin, d.adrelid) AS def, a.attidentity, a.attgenerated
      FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
      WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`, [t.oid]);
    const lineas = cols.map(c => {
      let tipo = c.tipo;
      let def = c.def;
      const esSerial = def && /^nextval\('.*'::regclass\)$/.test(def);
      if (esSerial && tipo === 'integer') { tipo = 'SERIAL'; def = null; }
      else if (esSerial && tipo === 'bigint') { tipo = 'BIGSERIAL'; def = null; }
      else if (esSerial && tipo === 'smallint') { tipo = 'SMALLSERIAL'; def = null; }
      let l = `  ${id(c.attname)} ${tipo}`;
      if (c.attidentity === 'a') l += ' GENERATED ALWAYS AS IDENTITY';
      else if (c.attidentity === 'd') l += ' GENERATED BY DEFAULT AS IDENTITY';
      else if (c.attgenerated === 's') l += ` GENERATED ALWAYS AS (${def}) STORED`;
      else if (def) l += ` DEFAULT ${def}`;
      if (c.attnotnull && !esSerial) l += ' NOT NULL';
      return l;
    });
    out.push('');
    out.push(`CREATE TABLE ${id(t.relname)} (\n${lineas.join(',\n')}\n);`);
  }

  // Restricciones: primero PK/UNIQUE/CHECK, al final FK (para no depender del orden de tablas)
  const cons = await q(`
    SELECT c.relname AS tabla, k.conname, k.contype, pg_get_constraintdef(k.oid) AS def
    FROM pg_constraint k JOIN pg_class c ON c.oid = k.conrelid JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND k.contype IN ('p','u','c','f') ORDER BY c.relname, k.conname`);
  out.push('');
  for (const tipo of ['p', 'u', 'c', 'f']) {
    for (const k of cons.filter(x => x.contype === tipo)) {
      out.push(`ALTER TABLE ${id(k.tabla)} ADD CONSTRAINT ${id(k.conname)} ${k.def};`);
    }
  }

  // Índices que no respaldan una restricción
  const nombresCons = new Set(cons.map(k => k.conname));
  const idx = await q(`SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = 'public' ORDER BY tablename, indexname`);
  const sueltos = idx.filter(i => !nombresCons.has(i.indexname));
  if (sueltos.length) out.push('');
  for (const i of sueltos) out.push(i.indexdef.replace(/^CREATE (UNIQUE )?INDEX/, 'CREATE $1INDEX IF NOT EXISTS') + ';');

  // Cosas que este script NO copia
  const vistas = await q(`SELECT count(*)::int n FROM pg_views WHERE schemaname = 'public'`);
  const funcs = await q(`SELECT count(*)::int n FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public'`);
  const trig = await q(`SELECT count(*)::int n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND NOT t.tgisinternal`);
  if (vistas[0].n) avisos.push(`${vistas[0].n} vista(s)`);
  if (funcs[0].n) avisos.push(`${funcs[0].n} función(es)`);
  if (trig[0].n) avisos.push(`${trig[0].n} trigger(s)`);

  const destino = path.join(__dirname, 'schema.sql');
  fs.writeFileSync(destino, out.join('\n') + '\n');
  console.log(`Listo: ${tablas.length} tablas, ${cons.length} restricciones, ${sueltos.length} índices -> ${destino}`);
  if (avisos.length) console.log('OJO: tu base tiene ' + avisos.join(', ') + ' que este script NO copia. Avísame para agregarlos.');
  await pool.end();
})().catch(e => { console.error('Error:', e.message); process.exit(1); });
